
package semcamadas;

/**
 *
 * @author Abigail
 * 
 */

public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        BarraDeFerramentas = new javax.swing.JMenuBar();
        MenuRelatorio = new javax.swing.JMenu();
        ResumoGeral = new javax.swing.JMenuItem();
        ResumoDepartamentos = new javax.swing.JMenuItem();
        resumoFuncionarios = new javax.swing.JMenuItem();
        MenuDepartamentos = new javax.swing.JMenu();
        addDepartamento = new javax.swing.JMenuItem();
        departamentos = new javax.swing.JMenuItem();
        MenuFuncionarios = new javax.swing.JMenu();
        addFunc = new javax.swing.JMenuItem();
        funcionarios = new javax.swing.JMenuItem();
        busca = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro da Universidade");
        setName("telaInicial"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 400));

        MenuRelatorio.setText("Relatório");

        ResumoGeral.setText("Resumo Geral");
        MenuRelatorio.add(ResumoGeral);

        ResumoDepartamentos.setText("Resumo dos Departamentos");
        MenuRelatorio.add(ResumoDepartamentos);

        resumoFuncionarios.setText("Resumo dos Funcionarios");
        MenuRelatorio.add(resumoFuncionarios);

        BarraDeFerramentas.add(MenuRelatorio);

        MenuDepartamentos.setText("Departamentos");

        addDepartamento.setText("Adicionar Departamento");
        addDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartamentoActionPerformed(evt);
            }
        });
        MenuDepartamentos.add(addDepartamento);

        departamentos.setText("Departamentos");
        MenuDepartamentos.add(departamentos);

        BarraDeFerramentas.add(MenuDepartamentos);

        MenuFuncionarios.setText("Funcionarios");

        addFunc.setText("Adicionar Funcionarios");
        addFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFuncActionPerformed(evt);
            }
        });
        MenuFuncionarios.add(addFunc);

        funcionarios.setText("Funcionarios");
        MenuFuncionarios.add(funcionarios);

        busca.setText("Buscar Funcionario");
        MenuFuncionarios.add(busca);

        BarraDeFerramentas.add(MenuFuncionarios);

        setJMenuBar(BarraDeFerramentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFuncActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroFuncionario().setVisible(true);
        });
    }//GEN-LAST:event_addFuncActionPerformed

    private void addDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartamentoActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroDepartamento().setVisible(true);
        });
    }//GEN-LAST:event_addDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeFerramentas;
    private javax.swing.JMenu MenuDepartamentos;
    private javax.swing.JMenu MenuFuncionarios;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem ResumoDepartamentos;
    private javax.swing.JMenuItem ResumoGeral;
    private javax.swing.JMenuItem addDepartamento;
    private javax.swing.JMenuItem addFunc;
    private javax.swing.JMenuItem busca;
    private javax.swing.JMenuItem departamentos;
    private javax.swing.JMenuItem funcionarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem resumoFuncionarios;
    // End of variables declaration//GEN-END:variables
}
